<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>station</name>
  <version>0.0.1</version>
  <description>Ground station node: mission coordination and drone tasking for the Archangel project.</description>
  <maintainer email="jeanbaptistekwi@gmail.com">jbkwizera</maintainer>
  <license>TODO: License declaration</license>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>archangel_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>drone_agent</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>sim_assets</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>perception</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
